- name: software | alacritty | install alacritty
  become: true
  package:
    name:
      - alacritty
    state: latest

- name: software | alacritty | create config directory
  file:
    path: /home/tobiasz/.config/alacritty
    state: directory

- name: software | alacritty | copy alacritty config
  copy:
    src: "{{ playbook_dir }}/tasks/software/alacritty/config.yaml"
    dest: /home/tobiasz/.config/alacritty
    owner: tobiasz
    group: tobiasz