# TODO: compile from source instead
#- name: software | alacritty | install alacritty
#  become: true
#  package:
#    name:
#      - alacritty
#    state: latest

- name: software | alacritty | ensure config directory
  file:
    path: "/home/{{ the_user }}/.config/alacritty"
    state: directory

- name: software | alacritty | copy alacritty config
  become_user: "{{ the_user }}"
  copy:
    src: "{{ playbook_dir }}/tasks/software/alacritty/alacritty.yaml"
    dest: "/home/{{ the_user }}/.config/alacritty"
