- name: software | alacritty | install alacritty
  become: true
  package:
    name:
      - alacritty
    state: latest

- name: software | alacritty | ensure config directory
  file:
    path: "/home/{{ the_user }}/.config/alacritty"
    state: directory

- name: software | alacritty | copy alacritty config
  copy:
    src: "{{ playbook_dir }}/tasks/software/alacritty/alacritty.yaml"
    dest: "/home/{{ the_user }}/.config/alacritty"
    owner: "{{ the_user }}"
    group: "{{ the_user }}"