- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | include user settings
      include_vars: user-settings.yaml

    - name: pre-run | update package cache
      tags: always
      apt: update_cache=yes
      changed_when: False
  tasks:
    - import_tasks: "tasks/users/{{ the_user }}.yaml"

    - import_tasks: tasks/software/packages.yaml
      vars:
        task_enabled: "{{ vars[the_user].software.packages }}"
      when: task_enabled|bool

    - import_tasks: tasks/software/ssh.yaml
      vars:
        task_enabled: "{{ vars[the_user].software.ssh }}"
      when: task_enabled|bool

    - import_tasks: tasks/software/git/git.yaml
      vars:
        task_enabled: "{{ vars[the_user].software.git }}"
      when: task_enabled|bool

    - import_tasks: tasks/software/secrets.yaml
      vars:
        task_enabled: "{{ vars[the_user].software.secrets }}"
      when: task_enabled|bool

    - name: "docker token"
      debug:
        msg: "docker token: {{ docker_token }}"

    - import_tasks: tasks/automation/user/user.yaml
      vars:
        automation_enabled: "{{ vars[the_user].automation.enabled }}"
      when: automation_enabled|bool

    - import_tasks: tasks/automation/rerun_ansible.yaml
      vars:
        task_enabled: "{{ vars[the_user].automation.monitor_settings }}"
        automation_enabled: "{{ vars[the_user].automation.enabled }}"
      when: task_enabled|bool and automation_enabled|bool
