- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | include user settings
      include_vars: user-settings.yaml

    - name: pre-run | update package cache
      tags: always
      apt: update_cache=yes
      changed_when: False
  tasks:
    - import_tasks: "tasks/users/{{ the_user }}.yaml"

    - name: Print the gateway for each host when defined
      vars:
        task_enabled: {{ vars[the_user].software.packages }}
      debug:
        msg: var = {{ task_enabled }}

    - import_tasks: tasks/software/packages.yaml
      vars:
        task_enabled: "{{ the_user }}['software']['packages']"
      when: task_enabled|bool

    - import_tasks: tasks/automation/user/user.yaml
      vars:
        automation_enabled: "{{ the_user }}['automation']['enabled']"
      when: automation_enabled == True

    - import_tasks: tasks/automation/rerun_ansible.yaml
      vars:
        task_enabled: "{{ the_user }}['automation']['monitor-settings']"
        automation_enabled: "{{ the_user }}['automation']['enabled']"
      when: task_enabled == True and automation_enabled == True
