tobiasz:
  automation:
  software:
    git: True
    alacritty: True
    fonts: True
    i3: True
    nvim: True
    polybar: True
    rofi: True
    tmux: True
    useful_scripts: True
    wallpaper: True
    xfiles: False
    zsh: True
    ansible: True
    bitwarden: False
    code: False
    discord: True
    docker: False
    lazydocker: True
    kubernetes: False
    font_manager: False
    fzf: False
    golang: False
    jetbrains_toolbox: True
    latex: False
    lua: True
    notes: False
    nvm: True
    packages: True
    peek: False
    postman: True
    python: True
    rust: True
    sdkman: True
    secrets: True
    slack: False
    ssh: True
    terraform: False
    themes: False
    thunderbird: True
    tmux_workspaces: True
    vagrant: False
    virtualbox: False
    x11_packages: False
    zathura: False
    zoom: True

toz:
  automation:
    enabled: True
  software:
    git: True
    alacritty: True
    fonts: True
    i3: True
    nvim: True
    polybar: True
    rofi: True
    tmux: True
    useful_scripts: True
    wallpaper: True
    xfiles: True
    zsh: True
    ansible: True
    bitwarden: True
    code: True
    discord: False
    docker: False
    lazydocker: True
    kubernetes: False
    font_manager: False
    fzf: True
    golang: True
    jetbrains_toolbox: True
    latex: False
    lua: True
    notes: True
    nvm: False
    packages: True
    peek: False
    postman: True
    python: True
    rust: True
    sdkman: False
    secrets: True
    slack: True
    ssh: True
    terraform: False
    themes: True
    thunderbird: False
    tmux_workspaces: True
    vagrant: False
    virtualbox: False
    x11_packages: True
    zathura: True
    zoom: False
