tobiasz:
  automation:
    enabled: True
    monitor_settings: True
  software:
    git: True
    alacritty: True
    fonts: True
    i3: True
    nvim: True
    polybar: True
    rofi: True
    tmux: True
    useful_scripts: True
    wallpaper: True
    xfiles: True
    zsh: True
    ansible: True
    bitwarden: True
    code: True
    discord: True
    docker: True
    lazydocker: True
    kubernetes: True
    font_manager: True
    fzf: True
    golang: True
    jetbrains_toolbox: True
    latex: True
    lua: True
    notes: True
    nvm: True
    packages: True
    peek: True
    postman: True
    python: True
    rust: True
    sdkman: True
    secrets: True
    slack: True
    ssh: True
    terraform: True
    themes: True
    thunderbird: True
    tmux_workspaces: True
    vagrant: True
    virtualbox: True
    x11_packages: True
    zathura: True
    zoom: True

toz:
  automation:
    enabled: False
  software:
    git: True
    alacritty: True
    fonts: True
    i3: True
    nvim: True
    polybar: True
    rofi: True
    tmux: True
    useful_scripts: True
    wallpaper: True
    xfiles: True
    zsh: True
    ansible: True
    bitwarden: True
    code: True
    discord: False
    docker: True
    lazydocker: True
    kubernetes: False
    font_manager: True
    fzf: True
    golang: True
    jetbrains_toolbox: True
    latex: False
    lua: True
    notes: True
    nvm: True
    packages: True
    peek: True
    postman: True
    python: True
    rust: True
    sdkman: True
    secrets: True
    slack: True
    ssh: True
    terraform: False
    themes: True
    thunderbird: False
    tmux_workspaces: True
    vagrant: False
    virtualbox: False
    x11_packages: True
    zathura: True
    zoom: False
