tobiasz:
  automation:
    enabled: true
    monitor-settings: true
  software:
    git: true
    alacritty: true
    fonts: true
    i3: true
    nvim: true
    polybar: true
    rofi: true
    tmux: true
    useful-scripts: true
    wallpaper: true
    xfiles: true
    zsh: true
    ansible: true
    bitwarden: true
    code: true
    discord: true
    docker: true
    lazydocker: true
    kubernetes: true
    font-manager: true
    fzf: true
    golang: true
    jetbrains-toolbox: true
    latex: true
    lua: true
    notes: true
    nvm: true
    packages: true
    peek: true
    postman: true
    python: true
    rust: true
    sdkman: true
    secrets: true
    slack: true
    ssh: true
    terraform: true
    themes: true
    thunderbird: true
    tmux-workspaces: true
    vagrant: true
    virtualbox: true
    x11-packages: true
    zathura: true
    zoom: true

toz:
  automation:
    enabled: true
  software:
    git: true
    alacritty: true
    fonts: true
    i3: true
    nvim: true
    polybar: true
    rofi: true
    tmux: true
    useful-scripts: true
    wallpaper: true
    xfiles: true
    zsh: true
    ansible: true
    bitwarden: true
    code: true
    docker: true
    lazydocker: true
    font-manager: true
    fzf: true
    golang: true
    jetbrains-toolbox: true
    lua: true
    notes: true
    nvm: true
    packages: true
    peek: true
    postman: true
    python: true
    rust: true
    sdkman: true
    secrets: true
    slack: true
    ssh: true
    themes: true
    tmux-workspaces: true
    virtualbox: true
    x11-packages: true
    zathura: true
