- name: software | useful-scripts | copy scripts
  become_user: "{{ the_user }}"
  copy:
    src: "{{ playbook_dir }}/tasks/software/useful-scripts/{{ item.name }}"
    dest: "/home/{{ the_user }}/.local/bin/{{ item.name }}"
  with_items:
    - { name: 'dark-chrome' }
    - { name: 'google-java-format' }
    - { name: 'search-history' }
    - { name: 'set-vol.sh' }
    - { name: 'stress-test' }
    - { name: 'sync-worktree' }
    - { name: 'util' }
