- name: software | useful-scripts | copy scripts
  copy:
    src: {{ playbook_dir }}/tasks/software/useful-scripts/{{ item.name }}
    dest: /home/tobiasz/.local/bin/{{ item.name }}
    owner: tobiasz
    group: tobiasz
  with_items:
    - { name: 'dark-chrome' }
    - { name: 'google-java-format' }
    - { name: 'search-history' }
    - { name: 'set-vol.sh' }
    - { name: 'stress-test' }
    - { name: 'sync-worktree' }
    - { name: 'util' }
