- name: software | git | install git
  package:
    name: git
    state: latest

- name: software | git | ensure git files
  become_user: "{{ the_user }}"
  copy:
    src: "{{ playbook_dir }}/tasks/software/git/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'gitconfig', dest: '/home/{{ the_user }}/.gitconfig' }
    - { src: 'gitignore', dest: '/home/{{ the_user }}/.gitignore' }
