- name: software | fonts | copy fonts
  copy:
    src: "{{ playbook_dir }}/tasks/software/fonts/my-fonts"
    dest: "/home/{{ the_user }}/.fonts"
    owner: "{{ the_user }}"
    group: "{{ the_user }}"
