- name: software | golang | remove old golang
  file:
    path: /usr/local/go
    state: absent

- name: software | golang | install golang
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes