- name: software | golang | install golang
  package:
    name: golang-go
    state: latest

- name: software | golang | ensure golang directories
  file:
    path: "/home/{{ the_user }}/go/{{ item.dir }}"
    state: directory
  with_items:
    - { dir: 'bin' }
    - { dir: 'src' }
    - { dir: 'pkg' }