- name: software | kubernetes | ensure apt signing key for kubernetes
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/kubernetes.asc
    mode: '0644'
    force: true

- name: software | kubernetes | ensure apt repository for kubernetes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/kubernetes.asc] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes.list

- name: software | kubernetes | install kubectl
  apt:
    name: kubectl
    state: latest
    update_cache: true

- name: software | kubernetes | install/update helm snap
  snap:
    name:  helm
    state: present
    classic: true

- name: software | kubernetes | check if minikube exists
  shell: command -v minikube
  register: minikube_exists
  ignore_errors: yes

- name: software | kubernetes | install minikube
  when: minikube_exists is failed
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
    force: 'yes'

