- name: software | lazydocker | download installer
  get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: /tmp/install_update_lazydocker.sh
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: software | lazydocker | install lazydocker
  become_user: "{{ the_user }}"
  shell: /tmp/install_update_lazydocker.sh