- name: software | packages | install lua and luarocks
  package:
    name:
      - lua
      - luarocks
    state: latest

- name: software | lua | install luacheck
  shell: luarocks install luacheck

- name: software | lua | install lanes
  shell: luarocks install lanes

- name: software | lua | install stylua
  community.general.cargo:
    name: stylua
    state: latest

- name: software | lua | install tree-sitter-cli
  community.general.cargo:
    name: tree-sitter-cli
    state: latest
