- name: software | packages | install lua and luarocks
  package:
    name:
      - lua5.3
      - luarocks
      - liblua5.3-dev
    state: latest

- name: software | lua | install luacheck
  shell: luarocks install luacheck

- name: software | lua | install lanes
  shell: luarocks install lanes

- name: software | lua | install stylua
  shell: cargo install stylua
  args:
    executable: /bin/zsh

- name: software | lua | install tree-sitter-cli
  shell: cargo install tree-sitter-cli
  args:
    executable: /bin/zsh
