- name: software | nvm | check if nvm exists
  shell: command -v nvm
  register: nvm_exists
  ignore_errors: yes

- name: software | nvm | download installer
  when: nvm_exists is failed
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: /tmp/nvm_install.sh
    mode: '0755'
    force: 'yes'

- name: software | nvm | install nvm
  become_user: "{{ the_user }}"
  when: nvm_exists is failed
  shell: |
    /bin/bash /tmp/nvm_install.sh
    source /home/{{ the_user }}/.bashrc
  args:
    executable: /bin/bash

- name: software | nvm | install node
  when: nvm_exists is failed
  shell: |
    nvm install 16

- name: software | nvm | ensure npm packages
  shell: |
    npm install -g yarn
    npm install -g prettier
    npm install -g eslint
