- name: software | packages | install packages
  package:
    name:
      - software-properties-common
      - glances
      - htop
      - neofetch
      - ncdu
      - wget
      - curl
      - ripgrep
      - zip
      - unzip
      - xkeycaps
      - autokey-gtk
      - nmap
      - snapd
      - gcc
      - gnome-tweaks
      - make
      - build-essential
      - libssl-dev
      - libghc-zlib-dev
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - libffi-dev
      - libxml2-utils
      - gettext
      - git
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - vim
      - xclip
      - nala
    state: latest

- name: software | packages | install/update core snap
  snap:
    name:  core
    state: present
