- name: software | rust | check if cargo exists
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: software | rust | download installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: software | rust | install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust