- name: software | sdkman | check if sdkman exists
  shell: command -v sdk
  register: sdkman_exists
  ignore_errors: yes
  become_user: "{{ the_user }}"

- name: software | sdkman | download installer
  when: sdkman_exists is failed
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/get.sdkman.io
    mode: '0755'
    force: 'yes'

- name: software | sdkman | install sdkman
  become_user: "{{ the_user }}"
  when: sdkman_exists is failed
  shell: /tmp/get.sdkman.io
  args:
    executable: /bin/bash

- name: software | sdkman | ensure sdkman config
  become_user: "{{ the_user }}"
  file:
    path: /home/toz/{{ item.dir }}
    state: directory
  with_items:
    - { dir: .sdkman }
    - { dir: .sdkman/etc }

- name: software | sdkman | ensure sdkman config
  copy:
    dest: "/home/{{ the_user }}/.sdkman/etc/config"
    content: |
      sdkman_auto_answer=true
      sdkman_auto_complete=true
      sdkman_auto_env=false
      sdkman_auto_update=true
      sdkman_beta_channel=false
      sdkman_checksum_enable=true
      sdkman_colour_enable=true
      sdkman_curl_connect_timeout=7
      sdkman_curl_max_time=10
      sdkman_debug_mode=false
      sdkman_insecure_ssl=false
      sdkman_rosetta2_compatible=false
      sdkman_selfupdate_feature=true

- name: software | sdkman | install packages
  when: sdkman_exists is failed
  shell: |
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install java 17.0.5-tem
    sdk install java 8.0.352-tem
    sdk install java 11.0.17-tem
    sdk default java 17.0.5-tem
    sdk install maven 3.8.7
    sdk install gradle 7.6
