- name: software | secrets | clone secrets
  git:
    repo: git@github.com:tobias-z/secrets.git
    dest: "/home/{{ the_user }}/Documents/personal"
    clone: yes
    update: yes

- name: software | secrets | ensure secrets are loaded
  include_vars: "/home/{{ the_user }}/Documents/personal/secrets.yaml"