- name: software | tmux-workspaces | clone tmux-workspaces
  become_user: "{{ the_user }}"
  git:
    repo: git@github.com:tobias-z/tmux-workspaces.git
    dest: "/home/{{ the_user }}/dev/projects/tmux-workspaces"
    clone: yes
    update: yes

- name: software | tmux-workspaces | make tw script executable
  file:
    dest: "/home/{{ the_user }}/dev/projects/tmux-workspaces/src/tw"
    mode: a+x

