- name: software | x11-packages | install x11-packages
  package:
    name:
      - volumeicon-alsa
      - picom
      - flameshot
      - network-manager
      - network-manager-gnome
    state: latest
