- name: software | xfiles | ensure xfiles
  copy:
    src: "{{ playbook_dir }}/tasks/software/xfiles/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: tobiasz
    group: tobiasz
  with_items:
    - { src: 'xinitrc', dest: '/home/{{ the_user }}/.xinitrc' }
    - { src: 'Xmodmap', dest: '/home/{{ the_user }}/.Xmodmap' }
