- name: software | zsh | check if zsh exists
  stat:
    path: "/home/{{ the_user }}/.oh-my-zsh/README.md"
  register: zsh

- name: software | zsh | install zsh
  package:
    name: zsh
    state: latest

- name: software | zsh | make default shell zsh
  user:
    name: "{{ the_user }}"
    shell: /bin/zsh

- name: software | zsh | download oh my zsh installer
  when: not zsh.stat.exists
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh-install.sh
    mode: '0755'
    force: 'yes'

- name: software | zsh | install oh my zsh
  when: not zsh.stat.exists
  become_user: "{{ the_user }}"
  shell: /tmp/oh-my-zsh-install.sh --unattended --keep-zshrc
  args:
    executable: /bin/sh

- name: software | zsh | ensure spaceship prompt
  become_user: "{{ the_user }}"
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "/home/{{ the_user }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    clone: yes
    update: yes

- name: software | zsh | ensure symlink for spaceship prompt
  file:
    src: "/home/{{ the_user }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "/home/{{ the_user }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link

- name: software | zsh | ensure spaceship prompt
  become_user: "{{ the_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ the_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes
    update: yes

- name: software | zsh | ensure spaceship prompt
  become_user: "{{ the_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ the_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes

- name: software | zsh | copy zshrc
  become_user: "{{ the_user }}"
  copy:
    src: "{{ playbook_dir }}/tasks/software/zsh/zshrc"
    dest: "/home/{{ the_user }}/.zshrc"

- name: software | zsh | ensure zshenv file
  become_user: "{{ the_user }}"
  copy:
    dest: "/home/{{ the_user }}/.zshenv"
    content: |
      . "$HOME/.cargo/env"
  
      export DOCKER_TOKEN="{{ docker_token }}"
      export TF_TOKEN_app_terraform_io="{{ tf_token_app_terraform_io }}"
      export TF_TOKEN="{{ tf_token }}"
      export LINODE_TOKEN="{{ linode_token }}"
      export DIGITAL_OCEAN_TOKEN="{{ digital_ocean_token }}"
      export GITHUB_TOKEN="{{ github_token }}
