# It you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

export DOTFILES="$HOME/.config/nvim"
export PATH=$PATH:$HOME/.local/share/nvim/lsp_servers/lua-language-server/bin
export PATH=$PATH:/usr/local/go/bin
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
export GPG_TTY=$(tty)
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH=$HOME/dev/projects/tmux-workspaces/src:$PATH
export TW_CONFIG="$HOME/.config/tw"
export TW_PATHS="$HOME/dev/plugins $HOME/dev/projects $HOME/dev/devops $HOME/Documents $HOME/.config"
export TW_MAIN_WINDOW="main"
export PATH=$HOME/Documents/my-notes/bin:$PATH
# export PATH=$HOME/dev/scripts/containers/bin:$PATH
export PATH=$HOME/.local/share/JetBrains/Toolbox/scripts:$PATH
export PATH=$HOME/bin/.local/bin:$PATH
export PATH=/snap/bin:$PATH
export PATH=$HOME/.docker/cli-plugins:$PATH
export KUBECONFIG=".kubeconfig:$HOME/.kube/config"

export EDITOR=/usr/local/bin/nvim

export PATH="$HOME/.cargo/bin/alacritty/:$PATH"
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

# https://github.com/spaceship-prompt/spaceship-prompt
export SPACESHIP_CHAR_SYMBOL=〉
ZSH_THEME="spaceship"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

plugins=(
 git
 vi-mode
# zsh-vi-mode
 zsh-autosuggestions
 zsh-syntax-highlighting
 docker-compose
 docker
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
ZSH_DISABLE_COMPFIX="true"
#
#
# You may need to manually set your language environment
# export LANG=en_US.UTF-8

function zle-keymap-select zle-line-init {
    # change cursor shape in iTerm2
    case $KEYMAP in
        vicmd)      print -n -- "\E]50;CursorShape=0\C-G";;  # block cursor
        viins|main) print -n -- "\E]50;CursorShape=1\C-G";;  # line cursor
    esac

    zle reset-prompt
    zle -R
}

function zle-line-finish {
    print -n -- "\E]50;CursorShape=0\C-G"  # block cursor
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

bindkey -M viins 'jk' vi-cmd-mode

# For a full list of active aliases, run `alias`.
alias vim="nvim"
alias vi="nvim"
alias realvim="/usr/bin/vim"
alias nrt="npm run test"
alias nrs="npm run start"
alias nrd="npm run dev"
alias deletebranch="git branch --merged >/tmp/merged-branches && /usr/bin/nvim /tmp/merged-branches && xargs git branch -d </tmp/merged-branches"
alias luamake="$HOME/.local/share/nvim/lsp_servers/lua-language-server/3rd/luamake/luamake"
# alias python="python3"
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias k='kubectl'
alias ldocker="lazydocker"
alias k9s='docker run --rm -it -v "$(pwd)/.kubeconfig":/root/.kube/config quay.io/derailed/k9s'

updatenvim() {
    cd ~/dev/projects/neovim
    git pull
    make
    sudo make install
}

open() {
    if which xdg-open &> /dev/null; then
        xdg-open $@ &       # linux
    else
        open $@           # mac
    fi
}

apt() {
  command nala "$@"
}

sudo() {
  if [ "$1" = "apt" ]; then
    shift
    command sudo nala "$@"
  else
    command sudo "$@"
  fi
}

deploy() {
    npm run build
    scp -r ./build/* droplet:/var/www/$1
}

npmlink() {
    rm -rf dist/
    npm i
    npm run build
    rm -rf node_modules/
    npm link
}

nr() {
    npm run $1
}

extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjvf $1    ;;
      *.tar.gz)    tar xzvf $1    ;;
      *.bz2)       bzip2 -d $1    ;;
      *.rar)       unrar2dir $1    ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1    ;;
      *.tgz)       tar xzf $1    ;;
      *.zip)       unzip2dir $1     ;;
      *.Z)         uncompress $1    ;;
      *.7z)        7z x $1    ;;
      *.ace)       unace x $1    ;;
      *)           echo "'$1' cannot be extracted via extract()"   ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# h() {
#     local result=$(print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac --height "50%" | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g'))
#     zle reset-prompt
#     return $result
# }
# zle -N h
# bindkey -M viins '^R' h
# bindkey '^r' h

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"

if [ -z "$TMUX" ]; then
    tmux attach -t tobiasz || tmux new -s tobiasz
fi

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fpath+=${ZDOTDIR:-~}/.zsh_functions

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
