- name: software | tmux | install tmux
  package:
    name: tmux
    state: latest

- name: software | tmux | copy tmux config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ the_user }}"
    group: "{{ the_user }}"
  with_items:
    - { src: '{{ playbook_dir }}/tasks/software/tmux/tmux.conf', dest: '/home/{{ the_user }}/.tmux.conf' }
    - { src: '{{ playbook_dir }}/tasks/software/tmux/tmux-cht.sh', dest: '/home/{{ the_user }}/.local/bin' }
    - { src: '{{ playbook_dir }}/tasks/software/tmux/tmux-cht-command', dest: '/home/{{ the_user }}/.config/tmux' }
    - { src: '{{ playbook_dir }}/tasks/software/tmux/tmux-cht-languages', dest: '/home/{{ the_user }}/.config/tmux' }
