- name: software | nvim | install prerequisites
  package:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: latest

- name: software | nvim | check if nvim exists
  shell: command -v nvim
  register: nvim_exists
  ignore_errors: yes

- name: software | nvim | clone nvim
  when: nvim_exists is failed
  git:
    repo: git clone https://github.com/neovim/neovim
    dest: /home/tobiasz/dev/projects/neovim
    clone: yes
    update: yes

- name: software | nvim | build nvim
  when: nvim_exists is failed
  shell: |
    cd /home/tobiasz/dev/projects/neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install
    
- name: software | nvim | copy nvim config
  copy:
    src: {{ playbook_dir }}/tasks/software/nvim/nvim-config
    dest: /home/tobiasz/.config/nvim
    owner: tobiasz
    group: tobiasz

- name: software | nvim | ensure directories used for neovim
  file:
    path: {{ item.dir }}
    state: directory
  with_items:
    { dir: /home/tobiasz/.local/share/debuggers }
    { dir: /home/tobiasz/.local/share/jdtls }
    { dir: /home/tobiasz/.local/share/jdtls/workspaces }

- name: software | nvim | clone java-debug debugger
  git:
    repo: https://github.com/microsoft/java-debug
    dest: /home/tobiasz/.local/share/debuggers/java-debug
    clone: yes
    update: yes

- name: software | nvim | install java-debug debugger
  ansible.builtin.shell: ./mvnw clean install
  args:
    chdir: /home/tobiasz/.local/share/debuggers/java-debug

- name: software | nvim | clone vscode-java-test debugger
  git:
    repo: https://github.com/microsoft/vscode-java-test
    dest: /home/tobiasz/.local/share/debuggers/vscode-java-test
    clone: yes
    update: yes

- name: software | nvim | install vscode-java-test debugger
  ansible.builtin.shell: |
    npm install
    npm run build-plugin
  args:
    chdir: /home/tobiasz/.local/share/debuggers/vscode-java-test

